---
# DVWA role main.yml
- name: docker.io
  apt:
    force_apt_get: true
    name: docker.io
    state: present
    update_cache: true

- name: "Install pip3"
  apt:
    force_apt_get: true
    name: python3-pip
    state: present

- name: "Install Docker python module"
  pip:
    name: docker
    state: present

- name: "download and launch a docker web container"
  docker_container:
    image: cyberxsecurity/dvwa
    name: dvwa
    published_ports: "80:80"
    restart_policy: always
    state: started

- name: "Enable docker service"
  systemd:
    enabled: true
    name: docker
