---
# Heartbeat Role main.yml
- name: download heartbeat deb
  command: curl -L -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.9.2-amd64.deb
 
- name: install heartbeat deb
  command: dpkg --force-overwrite -i heartbeat-7.9.2-amd64.deb

- name: drop in heartbeat.yml 
  copy:
    src: /etc/ansible/roles/heartbeat/files/heartbeat-config.yml
    dest: /etc/heartbeat/heartbeat.yml

- name: setup heartbeat
  command: heartbeat setup

- name: start heartbeat service
  systemd: 
    name: heartbeat-elastic 
    state: started
    enabled: yes
