---
# Packetbeat Role main.yml
- name: download packetbeat deb
  command: curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.9.2-amd64.deb
 
- name: install packetbeat deb
  command: dpkg --force-overwrite,confnew -i packetbeat-7.9.2-amd64.deb

- name: drop in packetbeat.yml 
  copy:
    src: /etc/ansible/roles/packetbeat/files/packetbeat-config.yml
    dest: /etc/packetbeat/packetbeat.yml

- name: setup packetbeat
  command: packetbeat setup -e

- name: start packetbeat service
  systemd: 
    name: packetbeat
    state: started
    enabled: yes
